version: "3.7"

x-secrets: &secrets
  secrets:
    - docker_ssh_key

secrets:
  docker_ssh_key:
    file: ${HOME}/.ssh/id_rsa_docker
    
services:

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    hostname: redis
    restart: always
  
  tinker:
    depends_on:
      - redis
    ports:
      - "5678:5678"
      - "5000:5000"
