# Add to environment for all Bethel flask apps
x-flask-environment: &flask-environment
  INSTALL_LOCATION: ${INSTALL_LOCATION:-/srv/flask_app/logs}
  SENTRY_URL: ${SENTRY_URL:-}
  TEST_NAME: ${TEST_NAME:-'Test User'}
  TEST_USERNAME: ${TEST_USERNAME:-$USER}
  TEST_EMAIL: ${TEST_EMAIL:-testuser@bethel.edu}

# Add to flask apps that use the standard volumes
x-flask-volumes: &flask-volumes
  volumes:
    - .:/srv/flask_app
    - ${DATA_PATH:-./_data}/tmp:/tmp
    - ${DATA_PATH:-./_data}/logs:/srv/flask_app/logs

# Add to build args for all Bethel flask apps
x-common-build-args: &common-build-args
  ENVIRON: ${ENVIRON:-dev}

# Add to environment for services that use a redis cache
x-redis-environment: &redis-environment
  CACHE_REDIS_HOST: ${CACHE_REDIS_HOST:-redis}

services:

  tinker:
    build: 
      context: .
      target: ${BUILD_TARGET:-debug}
    container_name: tinker
    hostname: tinker
    environment:
      <<: [*flask-environment, *redis-environment]
      FLASK_APP: tinker:app
    restart: always
    <<: [*flask-volumes]
